pages:
  stage: deploy
  script:
    - apk add --no-cache bash  # install bash (only needed if not already installed)
    - bash -c 'shopt -s extglob && mkdir public && cp -r !(public) public/'
  artifacts:
    paths:
      - public
  only:
    - main